<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy by default</name>
  <uuid>8a1dc165-8306-44ec-9a9e-aad2216e75dc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Fix state name' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
