<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Remove duplicates</name>
  <uuid>48011dd7-0c16-48af-bd1d-80c1aa2ae6ad</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the street of 'Fix state name'  is the secondary address information of  'Fix state name'  
then
    set the secondary address information of decision to "" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
