<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>map</name>
  <uuid>c024998d-46ca-4435-ae20-f81386a32421</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the age is the age , 
		the children is the children , 
		the est income is the estimated income , 
		the gender is "M" , 
		the paymethod is "CC" , 
		the status is "S" , 
		the usage is the usage ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
