<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Discount into wallet for small transactions</name>
  <uuid>e1bac32b-5d4b-46b9-ba0b-85ea3dc4ebb7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if decision is Discount and 'Order amount' is less than 700
then
    set decision to Wallet ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
