<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>BusinessRule-2</name>
  <uuid>10a9979c-7ff9-404a-ae3c-42a2657dc3b6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the last oil change date of 'Car maintenance record' is in the year 2015
then
    set decision to true ;
    print "last maintenance date is too old" ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
