<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Add Coupon</name>
  <uuid>8599caf7-3136-4787-bdff-b117c5b33505</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the type of 'Best offer' is Coupon
then 
    add 'Best offer' to the offers of decision ; 
    print "Offer is Coupon: " + the value of 'Best offer' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
