<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>All F</name>
  <uuid>ee7a7ad1-cd3e-4093-8f2f-65b33dbdf4a7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
	set 'All F' to Prediction 
		where the predicted churn of each ML model output is "F" ;
	set 'number of predictions' to the number of elements in Prediction ;
if
	'number of predictions' is more than 0 
then
	set decision to a new ML model output where
		the confidence is the sum of the confidences of 'All F' / 'number of predictions' , 
		the predicted churn is "F" , 
		the weight is the sum of the weights of 'All F' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
