<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Default</name>
  <uuid>8d47b826-d547-4310-bda1-07da25083638</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 250 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
