<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Sum</name>
  <uuid>006a734f-aaa9-4ccf-9d46-547ec8651496</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the sum of the prices of Order ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
