<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>mapping</name>
  <uuid>2b5db91b-5f50-401a-b45c-7ec782af833a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
        the age is the age , 
        the car owner is "" , 
        the children is the children , 
        the est income is the estimated income , 
        the rateplan is 0 , 
        the usage is the usage ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
