<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>bccb779b-4f7a-4cb7-9f05-dd4eb40f9880</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0.5 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
