<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Gather weight results</name>
  <uuid>88305630-bb75-4de5-80e5-712a53ec714e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
    set 'message' to a string in the messages of 'Weight check' ;
if it is not true that 'Weight check' is compliant
then 
    decision does not get compliant ;
    add message to the messages of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
