<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>All LOW</name>
  <uuid>5203d1bc-99dd-4ab3-bbe9-0f474cfb96f9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
	set 'All LOW' to Prediction 
		where the predicted ltv of each ML model output is "LOW" ;
	set 'number of predictions' to the number of elements in Prediction ;
if
	'number of predictions' is more than 0 
then
	set decision to a new ML model output where
		the confidence is the sum of the confidences of 'All LOW' / 'number of predictions' , 
		the predicted ltv is "LOW" , 
		the weight is the sum of the weights of 'All LOW' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
