<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>adjust with revenue</name>
  <uuid>0ed8071c-7643-4ed3-81f8-6b8374c4f87f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the estimated income is more than 100000
then
	set decision to decision - 0.1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
