<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>4cd9aede-fcbc-446f-a00b-ea0ba9ddb37d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0.5 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
