<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>6f1084c2-84c0-4b73-8c2b-fa86836a911b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Result where
        the given discount is 0 , 
        the price is 0 , 
        the loyalty points is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
