<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ltv</name>
  <uuid>0b2ddfd2-bb70-444c-aa9d-d8231f9f9401</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the rawresult of RawResult ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
