<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Short ZIP+4 code</name>
  <uuid>d40c1b82-0e1b-4017-bf4c-96881735f93d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the length of the ZIP code of Preprocessing is more than 5
 and
    the length of the ZIP code of Preprocessing is less than 10 
then
    set decision to "Error: Invalid ZIP+4 code." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
