<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Empty ZIP code</name>
  <uuid>2efa6ea5-b98a-401f-b5a1-e96c6d4b0932</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the ZIP code of Preprocessing  is empty 
then
    set decision to "Error: ZIP code is missing." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
