<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Short ZIP code</name>
  <uuid>b0fdf02c-8fef-41c3-b9ea-67bf396fa7ff</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the length of the ZIP code of Preprocessing  is less than 5 
then
    set decision to "Error: Invalid ZIP code." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
