<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>29fc9371-9dea-4e9b-a7c2-930e7986a064</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
