<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Consiglio</name>
  <uuid>77886a36-1756-4fd2-a01d-ecc2dfea5b7d</uuid>
  <locale>it_IT</locale>
  <definition><![CDATA[se
	Nome è definito 
allora
	assegna decisione a `Salve { Nome }! { 'Consiglio meteo' }` ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
