<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>5 pc off on Cosmetics</name>
  <uuid>db48dae5-705c-4308-a77c-fb8681a48a8c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if there is at least one Item in Order where the name of this Item contains "Cosmetics" ,

then

set decision to a new Coupon where
        the amount is 0.05 , 
        the description is "10% off on cosmetics" , 
        the label is "Cosmetics 5" , 
        monetary is false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
