<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Determine churn probability</name>
  <uuid>db80147b-5027-41fb-a9ef-96bf2327467b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	the predicted churn is "T" 
then
	set decision to the confidence ;
else
	set decision to 1 - the confidence ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
