<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>All MEDIUM_HIGH</name>
  <uuid>3f02373e-6fd3-4bac-bf78-45e35b8744a6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
	set 'All MEDIUM_HIGH' to Prediction 
		where the predicted ltv of each ML model output is "MEDIUM_HIGH" ;
	set 'number of predictions' to the number of elements in Prediction ;
if
	'number of predictions' is more than 0 
then
	set decision to a new ML model output where
		the predicted ltv is "MEDIUM_HIGH" , 
		the confidence is the sum of the confidences of 'All MEDIUM_HIGH' / 'number of predictions' , 
		the weight is the sum of the weights of 'All MEDIUM_HIGH' , 
		the rank is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
