<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>eba1852e-db0e-43b1-b245-fa0cbecede0e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Error: Invalid State name." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
