<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Build total fees</name>
  <uuid>1d49722b-57d0-4375-8ef3-62eb4c044ba2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Extra bag fees' + 'Extra weight fees' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
