<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Determine extra weight</name>
  <uuid>dafaa998-6530-41c0-a1cb-7f8a856a7e08</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 'Total weight' is more than 'Weight allowance' 
then
    set decision to 'Total weight' - 'Weight allowance' ;
else 
    set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
