<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Add errors and warnings</name>
  <uuid>dfec47b8-d1c8-4cdc-b0b4-797a8148975e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set the errors of decision to 'Errors and warnings' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
