<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Remove the first 100</name>
  <uuid>b836b721-42e8-4658-afbc-2791769a17b8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Purchase is at least 100
then
    set decision to Purchase - 100 ;
else set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
