<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check width</name>
  <uuid>ee20caca-9884-481a-9c07-8c2461afd1e6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
    set 'maxwidth' to the width of the size and weight limits ;
if there is at least one Baggage Item in the bags 
    where the width is more than maxwidth , then decision does not get compliant ;
    add `At least one baggage is too wide. The maximum allowed width is { maxwidth  * 100 }cm or { round( maxwidth  * 100 / 2.54 , 0 ) } inches` to the messages of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
