<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check depth</name>
  <uuid>a571a17a-afc3-4f1a-a408-b020e4130c3c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
    set 'maxdepth' to the depth of the size and weight limits ;
if there is at least one Baggage Item in the bags 
    where the depth is more than maxdepth , then decision does not get compliant ;
    add `At least one baggage is too deep. The maximum allowed depth is { maxdepth * 100 }cm or { round( + maxdepth * 100 / 2.54 ,  0 ) } inches.`   to the messages of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
