<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Empty street field</name>
  <uuid>5f47f40e-95a1-4092-8ae1-6f3223929b64</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the street of  Preprocessing  is empty
then
    set decision to "Error: Street address is missing." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
