<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check compliance</name>
  <uuid>b26087df-373b-452b-bc15-930af18bfe63</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
    set 'compliance' to the baggage compliance computed from 
    baggage being 'Checked Baggage' ;

if compliance is defined and compliance is not compliant then
    set decision to compliance ;
    set the fee of decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
