<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get extra fees</name>
  <uuid>f978ae37-6439-4465-af51-c041cebd3ae9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[decision gets compliant ;
set the fee of decision to the baggage pricing computed from 
    Checked baggage being 'Checked Baggage' , 
    Initial booking being 'Initial Booking' , 
    Frequent flyer status being 'Frequent Flyer Status' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
