<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>City</name>
  <uuid>a7908944-3dc6-4944-9491-3025b6a0e94a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    City  is not empty
then
    add City to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
