<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Sanity check</name>
  <uuid>73822c52-bf1c-4a82-bf8c-1624ac161b3f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if there are more than 3 strings in decision where each string contains "Error" ,
then
    add "Error: Too many errors." to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
