<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ZIP code</name>
  <uuid>530eddb9-bb1b-4b83-8d94-68791de43c80</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    ZIP is not empty
then
    add ZIP to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
