<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>State and ZIP</name>
  <uuid>5d1e3830-691c-4dc0-ba14-d830aadbfc49</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 'State and ZIP'  is not empty   
then
    -- State is correct, so let's highlight Zip inconsistency
    add 'State and ZIP'  to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
