<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Street address</name>
  <uuid>d7beda0c-8c93-4079-9f87-151b4365bea2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Street  is not empty 
then
    add Street  to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
