<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Unique</name>
  <uuid>e31381a3-70b7-4777-ab22-14ac97149832</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each characteristic called 'candidate' , in Prediction 
if
	there is no characteristic in decision 
		where the name of candidate is the name of this characteristic ,
then
	add candidate to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
