<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy by default</name>
  <uuid>345d5fb0-2ae0-49bd-8af8-81a11a6286e2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Preprocessing ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
