<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Compute order amount after discount</name>
  <uuid>f3dc5fc6-a15e-4594-a4ed-f3e1de5b1647</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Best offer' is defined and the type of 'Best offer' is Discount
then
    set decision to 'Order amount' - the value of 'Best offer' ;
else
    set decision to 'Order amount' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
