<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Sum</name>
  <uuid>4f6b79d2-98ab-443b-98aa-81a39686f253</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Volume discount' + 'Status discount' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
