<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy by default</name>
  <uuid>9c297342-0444-4a50-bcbe-0d2202479e87</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to address ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
