<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Short city name</name>
  <uuid>8a176e3f-0901-438e-a09b-9008a82f0a94</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the length of the city of Preprocessing  is less than 3 
then
    set decision to "Warning: City name is too short." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
