<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Empty city field</name>
  <uuid>b3449c7b-969b-4f89-8f24-57f319e85c89</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the city of Preprocessing  is empty
then
    set decision to "Error: City name is missing." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
