<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>All AVERAGE</name>
  <uuid>e89cc090-a5da-47a1-be8d-85c4da2b8c37</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
	set 'All AVERAGE' to Prediction 
		where the predicted ltv of each ML model output is "AVERAGE" ;
	set 'number of predictions' to the number of elements in Prediction ;
if
	'number of predictions' is more than 0 
then
	set decision to a new ML model output where
		the confidence is the sum of the confidences of 'All AVERAGE' / 'number of predictions' , 
		the predicted ltv is "AVERAGE" , 
		the weight is the sum of the weights of 'All AVERAGE' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
