<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Size and weight limits</name>
  <uuid>1a082ae3-cac2-458f-a880-aeb59d9718ce</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[-- In metric system (kg and m)
set decision to a new Baggage Item where
        the width is 1 , 
        the depth is 0.9 , 
        the height is 1.58 , 
        the weight is 30 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
