<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>All MEDIUM</name>
  <uuid>e42059fc-23ed-489d-880d-6870d82dc618</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
	set 'All MEDIUM' to Prediction 
		where the predicted ltv of each ML model output is "MEDIUM" ;
	set 'number of predictions' to the number of elements in Prediction ;
if
	'number of predictions' is more than 0 
then
	set decision to a new ML model output where
		the predicted ltv is "MEDIUM" , 
		the confidence is the sum of the confidences of 'All MEDIUM' / 'number of predictions' , 
		the weight is the sum of the weights of 'All MEDIUM' , 
		the rank is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
