<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>4785d46c-41da-44d4-80df-23becc8c1160</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0.0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
